const works = [
  {
    img: "/img/works/mediheal.png",
    title: "Mediheal",
    subtitle: "Hospital Management and Booking Application",
    description:
      "Mediheal is a full-featured hospital management platform designed with dedicated modules for users, doctors, and administrators. The application enables patients to book doctor appointments online, manage accounts, and communicate directly with healthcare professionals via real-time chat and video calls. Doctors and admins are provided with personalized dashboards to manage patients, appointments, and hospital operations efficiently.",
    features: [
      "Secure signup and login using OAuth and OTP verification for enhanced security",
      "JWT authentication with refresh tokens for session management and continuous access.",
      "Personalized user accounts with wallet management, booking history, and profile editing.",
      "Appointment booking with online payments powered by Stripe",
      "Real-time chat and video consultation using Socket.IO and ZEGOCLOUD",
      "Image upload and management via Cloudinary for efficient storage",
      "Repository Pattern for scalable and maintainable backend architecture",
      "Doctor dashboard for patient management, appointment history, and prescription generation",
      "Admin dashboard for doctor onboarding, user management, bed space allocation, and overall hospital operations control.",
    ],
    tech: {
      Frontend: ["React.js", "Tailwind CSS"],
      Backend: ["Node.js", "Express.js"],
      Database: ["MongoDB"],
      Authentication: ["JWT", "OAuth", "OTP"],
      RealTime: ["Socket.IO", "ZEGOCLOUD"],
      Payments: ["Stripe"],
      Cloud: ["Cloudinary"],
      Architecture: ["Repository Pattern"],
    },
    link: "https://mediheal.sinan-dev.in/home",
  },
  {
    img: "/img/works/fashion-arclight.png",
    title: "Fashion Arclight",
    subtitle: "E-commerce Website for Men's Wear",
    description:
      "E-commerce Website specializing in men's wear with user and admin modules.",
    features: [
      "Developed an e-commerce platform specializing in men’s wear with user and admin modules.",
      "Users can manage accounts, orders, wallets and utilize features such as wishlist, cart, search, and filters.",
      "Implemented purchase options featuring offers and coupons, with added functionality for users to leave reviews after purchases.",
      "Implemented user authentication using Nodemailer for email verification.",
      "Implemented RESTful APIs for seamless communication between frontend and backend.",
      "Integrated secure payment gateways including Razorpay, wallet options, and Cash on Delivery (COD).",
      "Utilized EJS (Templating Engine) for front-end development.",
      "Followed MVC architecture and created admin-side interfaces for various management tasks.",
      "Deployed using AWS Cloud Service, Nginx, Certbot, and PM2 for reliable, scalable, and secure performance.",
    ],
    tech: {
      Frontend: ["EJS"],
      Backend: ["Node.js", "Express.js"],
      Database: ["MongoDB"],
      Authentication: ["Nodemailer"],
      Payments: ["Razorpay", "Wallet", "Cash on Delivery"],
      Deployment: ["AWS", "Nginx", "Certbot", "PM2"],
      Architecture: ["MVC"],
    },
    link: "https://fashion-arclight.sinan-dev.in",
  },
  {
    img: "/img/works/gsm-nesi.png",
    title: "GSM NESI",
    subtitle: "E-commerce Platform for GSM Products",
    description:
      "An e-commerce platform for selling GSM products online, featuring dynamic product filtering, exclusive offers, and an admin dashboard for efficient management of categories, products, and promotions.",
    features: [
      "Users can browse products without login or signup and view detailed product information.",
      "Access the latest offers and deals for cost-effective purchases.",
      "Advanced product filtering options to help users find the right products easily.",
      "Secure and user-friendly checkout process.",
      "Admin dashboard provides insights into sales and quick progress tracking.",
      "Admin can dynamically manage categories, products, and offers from the backend.",
    ],
    tech: {
      Frontend: ["React.js", "Tailwind CSS"],
      Backend: ["Node.js", "Express.js"],
      Database: ["MongoDB"],
    },
    link: "https://gsm-nesi.sinan-dev.in/",
  },
  {
    img: "/img/works/brew-and-bite.png",
    title: "Brew & Bite Demo",
    subtitle: "Restaurant Website",
    description:
      "A demo website for a local restaurant, showcasing its menu, services, and contact information.",
    features: [
      "Users can browse the menu, view services, and contact the restaurant.",
      "The website is responsive and optimized for various devices.",
    ],
    tech: {
      Frontend: ["React.js", "Tailwind CSS", "Vite"],
    },
    link: "https://brew-and-bite.sinan-dev.in",
  },
  {
    img: "/img/works/typeless.png",
    title: "TypeLess",
    subtitle: "Chrome Extension for Smart Form Autofill",
    description:
      "TypeLess is a productivity-focused Chrome extension that helps users save their personal details once and automatically fill web forms across websites. The extension reduces repetitive typing by intelligently detecting form fields and filling them instantly through a button or keyboard shortcut while keeping user data stored locally for privacy.",
    features: [
      "Save personal details once and reuse them to autofill forms across different websites.",
      "One-click autofill and keyboard shortcut support for faster form filling.",
      "Dynamic form field detection using input attributes such as id, name, placeholder, and labels.",
      "Privacy-first design where all user data is stored locally using Chrome storage APIs.",
      "Clean popup interface for quick access and data management.",
      "Options page for managing and updating saved user information.",
      "Content scripts interact with web pages to detect and populate form fields.",
      "Background service worker manages extension events and communication between components.",
      "Designed using Manifest V3 architecture for modern Chrome extension compatibility.",
    ],
    tech: {
      Frontend: ["HTML", "CSS", "JavaScript"],
      ExtensionAPI: [
        "Chrome Extensions API",
        "Manifest V3",
        "Content Scripts",
        "Background Service Worker",
      ],
      Storage: ["Chrome Storage API"],
      Tools: ["Vite", "Git"],
    },
    link: "https://chromewebstore.google.com/",
  },
  {
    img: "/img/works/react-skeletonify.jpg",
    title: "React Skeletonify",
    subtitle: "Lightweight React Skeleton Loader Library",
    description:
      "React Skeletonify is a lightweight and customizable React library designed to improve user experience during data loading states. It allows developers to easily add skeleton loaders to their React applications with minimal setup. The library supports multiple skeleton components such as text, avatar, card, and image placeholders while maintaining full flexibility with styling and layout.",
    features: [
      "Lightweight React library for implementing skeleton loading placeholders.",
      "Pre-built skeleton components including text, avatar, image, and card loaders.",
      "Highly customizable styles and sizes to match different UI designs.",
      "Smooth loading animations for better perceived performance.",
      "Easy integration with any React project with minimal configuration.",
      "Reusable component-based architecture for scalable UI development.",
      "Supports modern React setups including Vite and Next.js.",
      "Designed to improve user experience during asynchronous data fetching.",
    ],
    tech: {
      Library: ["React.js"],
      Styling: ["CSS", "Tailwind CSS"],
      BuildTools: ["Vite"],
      PackageManager: ["npm"],
    },
    link: "https://npmjs.com/package/react-skeletonify",
  },
];
